---
Name: silverstripe-search-service
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\SearchService\Interfaces\BatchDocumentInterface.default:
    class: SilverStripe\SearchService\Service\BatchProcessor
    constructor:
      configuration: '%$SilverStripe\SearchService\Service\IndexConfiguration'

  SilverStripe\SearchService\Interfaces\BatchDocumentInterface.dataobject:
    class: SilverStripe\SearchService\DataObject\DataObjectBatchProcessor
    constructor:
      configuration: '%$SilverStripe\SearchService\Service\IndexConfiguration'

  SilverStripe\SearchService\Extensions\SearchServiceExtension:
    constructor:
      indexService: '%$SilverStripe\SearchService\Interfaces\IndexingInterface'
      configuration: '%$SilverStripe\SearchService\Service\IndexConfiguration'
      batchProcessor: '%$SilverStripe\SearchService\Interfaces\BatchDocumentInterface.dataobject'

  SilverStripe\SearchService\Tasks\SearchConfigure:
    constructor:
      indexService: '%$SilverStripe\SearchService\Interfaces\IndexingInterface'

  SilverStripe\SearchService\Tasks\SearchReindex:
    constructor:
      indexService: '%$SilverStripe\SearchService\Interfaces\IndexingInterface'
      configuration: '%$SilverStripe\SearchService\Service\IndexConfiguration'
      batchProcessor: '%$SilverStripe\SearchService\Interfaces\BatchDocumentInterface.default'

  SilverStripe\SearchService\Tasks\SearchClearIndex:
    constructor:
      indexService: '%$SilverStripe\SearchService\Interfaces\IndexingInterface'
      configuration: '%$SilverStripe\SearchService\Service\IndexConfiguration'
      batchProcessor: '%$SilverStripe\SearchService\Interfaces\BatchDocumentInterface.default'

  SilverStripe\SearchService\Service\DocumentFetchCreatorRegistry:
    constructor:
      dataObject: '%$SilverStripe\SearchService\DataObject\DataObjectFetchCreator'

  SilverStripe\SearchService\Service\IndexConfiguration:
    constructor:
      index_variant: '`SS_ENVIRONMENT_TYPE`'

  SilverStripe\SearchService\Service\DocumentBuilder:
    constructor:
      configuration: '%$SilverStripe\SearchService\Service\IndexConfiguration'
      registry: '%$SilverStripe\SearchService\Service\DocumentFetchCreatorRegistry'
